baseURL = 'https://corbinheist.github.io/champions-of-trevail'
languageCode = 'en-us'
title = 'Champions of Trevail'
theme = "hugo-book"
enableGitInfo = true

[params]
  BookSection = '*'
  BookRepo = 'https://github.com/corbinheist/champions-of-trevail/'

